// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzjrzdrjkkecnsegmnud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6anJ6ZHJqa2tlY25zZWdtbnVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDE5NTQsImV4cCI6MjA3NDIxNzk1NH0.C96wpJvTYCaRk1VR8jmyKu9yP3E9P28OHJECEqOnOXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});